### ISSUE TITLE
Multiple browser tabs opened after clicking the the link returned when uploading to door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1008]
When I click on the link returned after uploading a project to door43, it opens a browser tab for every upload done since the last time I loaded the app.

**Comment by cdwhitfield73** [comment]
I found a fix for this, but there is a small catch.  The link is now a "one time use" link.  When you click on it, it will open up your browser to the project, and then remove the "click listener" immediately.   So clicking on it a second time will do nothing.  But then next time you upload, the new link will only open one browser window with the current project, instead of being cumulative.
