### ISSUE TITLE
UDB tabs showing up blank

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1054]
I have a scripture project with multiple source texts, one of which is English ULB. When viewing a chunk in 3-column mode, I click on the UDB tab to see its content. I then click on the other source language tab to see the other source. When I click back on the English tab, the UDB tab is still shown in the foreground, but its text (as well as that all other chunks whose UDB tab was in the foreground) is not displayed. This is also true for tN and tQ projects.

**Comment by cdwhitfield73** [comment]
There are a few rare occasions where the UDB resource tab display is blank, due to how the HTML has to be injected for the scripture formatting to work.  This happens if you switch source texts while the UDB tab is active, or there are no other resource tabs for that chunk except UDB, or sometimes when you scroll away and come back while the UDB tab is selected. Per a conversation with Koz, the following solution was implemented: Whenever the UDB resource tab would show up blank, there is now text displayed that says "Click to display text".  Clicking on the text (or the UDB tab) will refresh the display.
