### ISSUE TITLE
The info link on the Update menu is incorrect

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1064]
When the info button is clicked a browser is opened to http://help.door43.org/en. The correct link is in 878. This may be a server redirect problem as it did work at one time.

**Comment by cdwhitfield73** [comment]
Actually, what is happening is that when you click on the link, it is trying to send you to http://help.door43.org/en/knowledgebase/9-translationstudio/docs/5-update-options, which is the link I was told to use.  However, that page no longer exists, which is why you are getting redirected to  http://help.door43.org/en.  They need to re-create the correct help desk page so that the link has something to point to.

**Comment by cdwhitfield73** [comment]
The page has been re-created and populated with the appropriate helpful information.  The link now works again.
