### ISSUE TITLE
Cannot read property 'languag...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#1104]
Notes
======
Cannot read property 'language_id' of undefined

Environment
======
Environment Key | Value
:--: | :--:
Version |11.1.0
Operating System | Darwin
Platform | darwin
Release | 15.6.0
Architecture | x64

Log History
======
```javascript
2017-03-06 14:47:6 I/ts-dashboard.html:1123:4: Feedback Sent
	https://api.github.com/repos/unfoldingWord-dev/ts-desktop/issues/1103
2017-03-06 14:55:45 E/ts-translate.html:724:4: 
	TypeError: Cannot read property 'language_id' of undefined
2017-03-06 14:56:32 E/ts-translate.html:724:4: 
	TypeError: Cannot read property 'language_id' of undefined

```

**Comment by cckozie** [comment]
This project was originally loaded in v11. The app later downgraded to v10, then upgraded back to v11. Now when opening the project I get the "TypeError: Cannot read property 'language_id' of undefined" message when attempting to open it. I also now imported it clean on another machine running build 118 and I get the same error when attempting to open it. 
[ar_mat_text_ulb.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/822496/ar_mat_text_ulb.zip)

**Comment by cdwhitfield73** [comment]
The issue here (in version 11.1) is that the only source listed for this project is a UDB source, which is now invalid.  There are two "fields" that have to do with sources.  The list of sources, and the "current source" property.  When I added code to strip out invalid UDB sources, I forgot to make sure to update the "current source" value.  So when you loaded this project in v11.1, the "current source" no longer existed in the list.  I have added code to fix this from builds 119 on.  This project "should" still load fine in versions 10 and 11, but even if it doesn't, I can't go back and fix that code base.
