### ISSUE TITLE
Footnote - UDB

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#1121]
See https://github.com/unfoldingWord-dev/ts-android/issues/1993

As an end-user I would like to see the footnote icon when there is a footnote in the UDB. (Just like how it shows in the ULB.)

This icon should show in the UDB both when it is being used as a resource and as a source text.

**Comment by cdwhitfield73** [comment]
@ChrisJarka Can you give me an example book/chapter/verse where a footnote exists, for testing?

**Comment by cdwhitfield73** [comment]
In Desktop, the footnote icon would already being showing up in the UDB as a source if there was a footnote, but now I have made changes so that it will also show up in the UDB as a resource.  However, based on the example given above, there are no footnotes identified in the UDB resource container.  This part will need to be fixed on the data side before any show up in tS.
