### ISSUE TITLE
Unexpected merge on project import

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#1145]
@cdwhitfield73 I had a project on build 129 that had one chunk with a merge conflict that resulted in the parse error message in that chunk. I didn't expect the parse error, so I exported the project to a drive that is shared with another computer running v11.0 to see if the parse error was detected there as well. It was. I then clicked on the chunk data and clicked the Resolve conflict button. I then went back to the build 129 machine and imported the project. I was presented the screen that indicated the project already existed and gave me the Cancel, Merge, and Overwrite options. I did not expect to get that dialog since it seems to me that the projects should have a shared history. 

Is this expected behavior because of the chunk with the conflict parse error?

**Comment by cdwhitfield73** [comment]
Any time you import a project and that same project name exists already, you will get the dialog asking if you want to merge, overwrite or cancel.  Even if it is the exact same project.  It does not compare git history at that point yet.  If you choose merge and the two projects have identical histories, then it just won't make any changes.

I think you may be confusing the import function with the export to Door43 function.  In that case, if the project on Door43 only has shared history with the copy that you are exporting (even though it may also have newer stuff) then it does the export without questioning it.  Importing was not written that way, it always questions when an existing project is found.

So yes, this sounds like the expected behavior.

**Comment by cckozie** [comment]
Ah yes, I think you're right about the confusion with export to door43 and some past behavior on Android.
