### ISSUE TITLE
Create the user manager

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#27]
refer to the module spec https://github.com/unfoldingWord-dev/ts-requirements/wiki/Module-Interfaces#tsuser

**Comment by neutrinog** [comment]
I need to write up the spec for this first.

**Comment by neutrinog** [comment]
take a look at  this for encryption. https://github.com/google/end-to-end
They mention a js encryption library. I've used some different js encryption libraries in the past but if Google's using it it must be good!

**Comment by neutrinog** [comment]
@cdwhitfield73 Here are a few items to change.

---
I just ran the tests and grunt yelled at me that the module `jsonfile` did not exist. Please update the `package.json` to include this module. The easiest way would be to run 
```
npm install jsonfile --save-dev
```
Do the same for the `md5` module

---
Also from the unit tests it looks like it's supposed to be creating the profile with the sum `41da76f0fc3ec62a6939e634bfb6a342` (for the tesetuser1 profile)  however that content is not being deleted after the tests run. Be sure to delete any generated files after the tests are finished running so that test content is not accidentally added to the repository and so that the test environment stays clean.

---
Add a unit test that ensures an exception is raised when instantiating the user module without a username.

---
In the commit method you are using an asynchronous write method. Therefore the return value may be erroneous. You can either change this to a synchronous method `writeFileSync` or update the method to be asynchronous. I would suggest updating the commit method to be asynchronous. e.g. commit will accept a callback.

otherwise looking good!

**Comment by cdwhitfield73** [comment]
For the jsonfile and md5 packages, I am not sure what is going on.  I
already did load them with the --save-dev command, they are showing up in
my package.json file, they were listed as changes to be including in the
pull request, and when I re-pull from the unfoldingWord repo, they are
still showing up and work on my end.  So I am not sure why they are not
being recognized on your end.

As for the testuser1 profile, yes, the goal is to simulate creating a new
user profile that did not exist.  I spent a LOT of time trying to figure
out the best way to handle this.  The way it works now is that the unit
test file starts by deleting the profile if it is there.  It then runs a
test to confirm it is gone (@NoFile) then recreates it and runs the rest of
the tests on it.  Then for the profile for user2 which should already exist
and have data in it, it checks to make sure it IS there, and then checks to
make sure the data is getting loaded into storage.  At the end of the
tests, both profiles remain in the test directory and then next time the
test is run, it deletes the first one again.  I thought about having it
delete it at the end of the tests instead, leaving a cleaner environment
for next time, but the "after" functions did not seem to work right and the
"before" ones work well.  And by deleting it at the start, it ensures that
the test will run.  Not sure what the issue is with having that file stay
on there since there is another profile on there already and there seem to
be other tests that use test data that stays there all the time.  I can try
and rework this some more if you really want, so let me know.

The last two issues are more issues with the module itself than the tests.
I knew there was still work to do on it and those items are on my list.

Thanks for the feedback.

**Comment by neutrinog** [comment]
ah ok. Don't worry about the lingering test file then. I wasn't sure if that would cause problems with the tests. If not it's ok to leave it.

**Comment by cdwhitfield73** [comment]
I completed all the changes you have asked for.  Except for encryption, the basic user module is complete.
