### ISSUE TITLE
rename import to restore and add an import button for importing raw content.

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#274]
right now "import" can import backups and raw content (usfm). We need to split this into `restore` for .studio and `import` for raw content.

**Comment by cdwhitfield73** [comment]
This issue is completed as far as changing the current import function into a restore function.  A new import button has been added for raw content, but there is no back end functionality for that process yet, so the button is currently hidden.  I suggest a new issue be started for creating the import functionality.

**Comment by RRohrssen** [comment]
Issue to implement Restore functionality #291
