### ISSUE TITLE
UI for translating tA modules

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#284]
Get mockup from Sam.

**Comment by RRohrssen** [comment]
Dependent on #234

**Comment by sampeckham** [comment]
If the translation of tA is going to happen inside the tS app then it makes sense to use the current structure and process that already exists.

So a flow would be:
- Start new project
- Choose Target Language
- tA should then be listed alongside, NT, OT and OBS

As far as UI the only changes or considerations are:
- Blind drafting seems out of place - is it a suitable approach for tA content? It maybe just Read and Checking Modes required.
- How is tA divided up, it has varying levels of granularity, the UI breaks the content into logical cards such as Chapters and Stories. It maybe helpful to break tA down further?

Further features maybe required/desired:
- Is tA in a similar or usable format that can be read into the app like other projects can?
- Where scripture is used in the intro, can I pull that from my Bible project of the same language?
-  Are web links automatically inserted over the same 'like for like' piece of text, or do they need to be assigned to the right sentence words after translation (a bit like verses are done now).

So that being said, I'm not sure how much "New UI" needs creating right now.

**Comment by RRohrssen** [comment]
The corresponding work to implement the UI changes is #284 and assigned to @cdwhitfield73

**Comment by RRohrssen** [comment]
This will be implemented later #283

**Comment by neutrinog** [comment]
@sampeckham here's what the source for tA will probably look like https://github.com/unfoldingWord-dev/ts-requirements/wiki/APIv3-Draft#translation-academy-ta It's broken up into volumes, manuals, and articles. 

tA will not need the blind draft mode. And I think the existing read mode as it exists for current translations will not be needed as well since we'll already have a UI for reading/navigating tA.

@jag3773 I think we discussed links could be inserted by clicking on a button to initiate a search for an existing article.

**Comment by jag3773** [comment]
@neutrinog Correct, users should be able to link to:

* [ ] Any URL
* [ ] Any other module in tA.  This step would require some sort of DB lookup or JSON file that lists all the modules so that they can choose from a drop down.

**Comment by jag3773** [comment]
Follow the tW paradigm.
