### ISSUE TITLE
Import USFM data

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#291]
This issue is completed as far as changing the current import function into a restore function. A new import button has been added for raw content, but there is no back end functionality for that process yet, so the button is currently hidden. I suggest a new issue be started for creating the import functionality.

**Comment by tjklemz** [comment]
@RRohrssen we have Restore working, but Import is not. (You have it backwards.)

**Comment by RRohrssen** [comment]
I may or may not have it incorrect. So, @cdwhitfield73 and @tjklemz I want to clarify the terminology. Hopefully, we get consistent on the terminology.

Import/Export is typically used in software to work with files that are **not** the raw (or native) file format. Think of Excel when you import/export CSV files. For tS import/export should be USFM.

Backup/Restore is used for creating a data copy at a point in time, and may be a native file format, or raw. I'm not sure what format tS stores data in. JSON? Other? Perhaps USFM also, and hence the confusion?

So, @cdwhitfield73 on #274 when you say that the "import button" has been added for raw content that seems [to me] to be mixing terminology. Since you mentioned RAW content I interpreted that as Restore.

Thoughts?

**Comment by cdwhitfield73** [comment]
@RRohrssen I was using the terminology that Joel used in creating the issue.  He referred to "raw content" as stuff from outside the app that would be in USFM, for example, and needed converted to the app format.  You are correct that backup and restore are used to make archived copies of the projects in their native format (the way the app stores them) and these functions are completed.  Now, we want to add functionality for exporting existing projects into USFM format (which is partly done) and importing data that is in USFM into the app (this is not done, except that I made a button for it in the UI, which is currently hidden until functionality can be added).  So this issue should be re-titled to add import functionality.  The main confusion was you and Joel using "raw" in opposite context.

**Comment by RRohrssen** [comment]
@cdwhitfield73 Ok. @neutrinog was part of a conversation in FL about that. So, I think we're all on the same page with this [now].

**Comment by vleong2332** [comment]
> He referred to "raw content" as stuff from outside the app that would be in USFM, for example, and needed converted to the app format.

For my own clarification, this issue is about importing USFM to what format? `.tstudio` or project folder?

**Comment by RRohrssen** [comment]
@neutrinog Do you have an answer for @vleong2332 regarding the internal format?

**Comment by neutrinog** [comment]
@vleong2332 importing to a Target Translation folder (see terminology [here](https://github.com/unfoldingWord-dev/ts-requirements/wiki/Terminology)). `.tstudio` is just an output format.

**Comment by neutrinog** [comment]
Details on importing USFM files can be found at https://github.com/unfoldingWord-dev/ts-requirements/wiki/Importing-a-Target-Translation#usfm-file

**Comment by neutrinog** [comment]
@cdwhitfield73 is there an import button in the menu that can be enabled for this or can we add one?

**Comment by jeremymlane** [comment]
@neutrinog There's already one there than can just be shown. I'll go ahead and use that one.

**Comment by jeremymlane** [comment]
@neutrinog From what I can tell, USFM doesn't include a way to specify language in a way that I can use to automatically determine which project the USFM file should be imported into. 

There's a couple things we could do. We can allow the user to choose which project the file gets imported into (this would limit the import to one file at a time), or we could come up with some kind of file naming scheme that we can use to auto-determine which project and target translation the import should be to. 

Thoughts?

**Comment by neutrinog** [comment]
@jeremymlane we probably need to have the user choose because there's no way to enforce the file name. @jag3773 will that work or did we miss something?

**Comment by jag3773** [comment]
Yes, the user should be able to choose the language.

**Comment by jeremymlane** [comment]
Thanks. Will do. I have the parsing pretty much completed, just need to finish the portion that places the parsed data into a target translation.

**Comment by neutrinog** [comment]
@jeremymlane where are we at on this?

**Comment by jag3773** [comment]
Use any and/or all of the files https://git.door43.org/BrainT/ULB-pt-br for testing.

**Comment by RRohrssen** [comment]
See https://github.com/unfoldingWord-dev/ts-requirements/issues/42

**Comment by jeremymlane** [comment]
@neutrinog It's pretty close. Parsing is done and I'm just finishing up the GUI side. I'll push up an update in the next few days. @jag3773 Thanks for the link, that'll help me verify everything is working correctly.

**Comment by neutrinog** [comment]
@jeremymlane see updated notes on https://github.com/unfoldingWord-dev/ts-requirements/wiki/Importing-a-Target-Translation#usfm-file. We forgot to include how to chunk up the usfm files. There's a file that defines these chunks and it will probably be bundled in the app for reference (so we don't have to download it).

**Comment by jeremymlane** [comment]
@neutrinog Thanks. I think everything is pretty much working. Currently I'm determining the chunks the same way loading a project was. I'm just finishing up merging in recent changes from develop branch and then I'll update the process to use the chunks.json files.

**Comment by jeremymlane** [comment]
@neutrinog I have most everything working here: https://github.com/jeremymlane/ts-desktop/tree/issue291 but a couple things:

1. The files that describe how to chunk up a file (eg. https://api.unfoldingword.org/bible/txt/1/mat/chunks.json) don't specify the last verse, so there's no way to know what the last verse of the last chunk is other than just pulling in whatever verses are at the end of that chapter in the USFM file. Is that okay, or is there a better way to do that?
2. Where should I place the chunk descriptions in the folder structure or does it not matter?
3. I still need to make a couple changes for zip source files.
4. Could I get another set of eyes on this to find any bugs so I can fix them before submitting a pull request?
5. The test is temporarily broken because of a change I just made, but I'll have it fixed shortly.

**Comment by neutrinog** [comment]
1. yes
2. I don't know what you mean "chunk descriptions". I'm assuming those can be ignored. All we need is the chunked text.

I'll try to look at this tomorrow.

**Comment by jeremymlane** [comment]
@neutrinog I believe all the items I mentioned are finished now and it should be good to go. It works well on Mac, but another set of eyes on Windows would be helpful before I submit the pull request for this.

**Comment by klappy** [comment]
@binu-alexander from BCS just requested this feature as a high priority for his teams as it is blocking for them. I've asked him to share some example real world files for us to explore. 

This helps give devs actual testing data and gives the user an idea of expectations prior to the release.

**Comment by binu-alexander** [comment]
[Matthew.usfm.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/204893/Matthew.usfm.zip)

**Comment by binu-alexander** [comment]
This is file translated in other tools such as paratext .... this doesn't have \p tag and other tags such as the section headings tag ... if we can import this into tStudio then we can translate and add the remaning tags ..

**Comment by binu-alexander** [comment]
We have 12 languages New Testament with such 'incomplete' usfm files as in without the minimum required tags ...  This import feature will help us transition into tStudio as our one stop translation tool and end up with 'complete' USFM files

**Comment by neutrinog** [comment]
@jeremymlane fyi we won't support importing zip for now. The ui for that would add a lot of complexity because we'd need to collect langauges and projects for each file in the zip. So *just* support `usfm` files for now. Also @cdwhitfield73 is finishing up the importing menu and is adding in ui support for importing usfm files as well. once his code get's pulled in you'll be able to hook in your backend code.

**Comment by neutrinog** [comment]
this is completed from my understanding except it needs to retrieve chunk info from the index as provided in https://github.com/unfoldingWord-dev/ts-desktop/pull/541

**Comment by cckozie** [comment]
Need a more user friendly error message, something that tells them what is wrong in words they can understand.
![usfm import error](https://cloud.githubusercontent.com/assets/8171759/15328377/46e4133a-1c1a-11e6-91d4-5d3c8fc894b0.jpg)

**Comment by cckozie** [comment]
Should we be stripping out formatting markers (\q, \li, etc) that we are not currently processing?

**Comment by cdwhitfield73** [comment]
@cckozie : The second issue (stripping markers) is already fixed in the newest code.  The first issue (error message) has two solutions...both being submitted now.  One, I added a user friendly error message with the technical error message in parenthesis below it.  Two, I fixed the problem that was causing your specific error!

**Comment by neutrinog** [comment]
@cdwhitfield73 @cckozie I'm not sure we want to strip out the unused markers. Perhaps @klappy can weigh in on this, but I'm guessing if they bring their own USFM they'll want to keep the markers.

**Comment by cckozie** [comment]
USFM import of file with invalid ID fails without any error message.
[php_usfm_badId.txt](https://github.com/unfoldingWord-dev/ts-desktop/files/270867/php_usfm_badId.txt)

**Comment by cdwhitfield73** [comment]
@cckozie Added error checking for invalid ID's.  If the ID is invalid, it now acts the same as if there is no ID, it asks the user to select the project manually.  Also, added additional error catching to catch any unforeseen issues with trying to read the ID, with user friendly error messages.  The s5 marker was not really an issue.  Your missing s5 marker file also still had the bad ID in it, which was causing the same problem.  Importing works with missing s5 markers already.

These changes have been included in my hotfix Pull Request which Joel has not merged and given you yet.

**Comment by klappy** [comment]
@neutrinog: I agree, that I don't think we should strip out the ones that they import from a USFM file. They could have put time and effort in that and want to maintain them if possible.

If we want to add the ability for it to be cleaned up, can we make that optional?

**Comment by cdwhitfield73** [comment]
Changed to leave extra markers (like \q and \b) in text instead of stripping them.

**Comment by cckozie** [comment]
Cannot import USFM if the project already exists on the device. Forced to cancel or overwrite (that's a Restore)

**Comment by cdwhitfield73** [comment]
One: This was the functionality that was decided upon as a group.  Merging would not be allowed when importing USFM.  You could only make a brand new project or overwrite an existing one.

Two: It's technically not a Restore just because you are overwriting.  Restore implies bringing back something you previously saved as a backup.

**Comment by cckozie** [comment]
One: Android merges USFM files.

Two: Depends what you mean by "you". We do allow Restoring other user's tstudio files.

**Comment by cckozie** [comment]
Tested on 8.0-2
We should not fail the entire import just because a chunk marker is missing.
We should import chunk text even if the verse markers are missing.

**Comment by cdwhitfield73** [comment]
Ok.  I agree that we don't always use the term "restore" in it's truest since, and it is mostly associated with overwriting.  Not really the main issues here.

As far as merging, I am aware that android allows it.  Joel and I had a discussion about this.  As I mentioned, the group decision was to NOT allow merging, but Android put it in "by mistake".  That doesn't mean I am going to automatically copy that mistake unless the "group" or the "product owner" changes the decision that was made on the intended functionality.

As for the next comment on missing markers.  First, chunk markers don't have any bearing on the importing.  It is not using them to define chunks and they can be there or not, it will not fail the import.  However verse markers and chapter markers MUST be there.  It is the only way to know where the data belongs.  There is a standard requirement written up (somewhere) that defines the minimum requirements that a USFM file must have in order to be used in tS and it specifies which markers are needed.  We can't write code that will magically import any file in any format with or without any kinds of markers and somehow know what to do with it.  I feel that you should only be testing the import function with files that meet the minimum spec, since we should not be required to handle files that don't.

**Comment by neutrinog** [comment]
agreed. The verse and chapter markers are required.

**Comment by cckozie** [comment]
Tested with 8.0.3
Fails entire import with missing Chapter 1 marker, but error message is still not useful for the user. 
![image](https://cloud.githubusercontent.com/assets/8171759/15521030/1f59bbac-21cf-11e6-9392-930ee3b3dba5.png)

It should be something more like:
Error importing project.
Missing chapter marker(s).

If you need to display the technical error for the programmer, then it should be in a smaller font and separated by at least 1 line feed from the user friendly text.

**Comment by cckozie** [comment]
If only the Chapter 2 marker is missing, then the text for chapter 2 shows up as chapter 1, the chunks for chapter 2 are blank, and the text for chapter 1 does not show up anywhere.
![image](https://cloud.githubusercontent.com/assets/8171759/15521445/777b0154-21d1-11e6-9fe9-1382bfe30f88.png)

**Comment by cdwhitfield73** [comment]
It WON'T WORK if the chapter and verse markers aren't all there!!!  You WILL get unexpected results.  The files need to be in USFM format, which means the chapters and verses have to be marked.  Otherwise the user will just need to copy and paste text into the app.  There is no reason to continue testing files that don't meet the requirements.  They will fail and there is no current plan to change the code to handle these scenarios!

**Comment by neutrinog** [comment]
@cdwhitfield73 we do need to account for missing chapters. If the chapter tag is missing that entire chapter should be skipped.

**Comment by cdwhitfield73** [comment]
I don't think this is as easy as you make it sound.  If, for example, the chapter 2 marker is missing, then it will appear that chapter 1 has two verse 1 markers, two verse 2 markers, etc.  Being able to ensure that we are getting the right data in the right chunks with any missing markers is going to take a major rewrite of how our current USFM parser works.  Before I do that, I would like to hear from @klappy on what the exact user story he would like to accomplish is and a confirmation that it is worth putting in the extra work.  My understanding of the current user story was to be able to import files that have all the markers.

**Comment by neutrinog** [comment]
The USFM can be easily parsed to avoid duplicate verses e.g.
```
\c 1, \v 1 \v 2 \v 3  [\c 2 is missing] \v 1 \v 3 \c 3 \v 1 \v 2 \v 3
```
Chapters should end first of all once it finishes looping through the chunks defined in chunks.json but secondarily if it encounters a duplicate verse in that chapter.

The result would be chapter one with verses 1-3 and chapter three with verses 1-3. Chapter two would be skipped entirely due to corruption.
