### ISSUE TITLE
add a migration step for new TargetTranslation manifest

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#364]
See https://github.com/unfoldingWord-dev/ts-requirements/issues/25

The new manifest spec is at https://github.com/unfoldingWord-dev/ts-requirements/wiki/ts.Translator.TargetTranslation#manifest-structure

In particular the change involves the translators array becoming an array of names rather than of objects containing sensitive information.

A new migration method needs to be added to `js/migration/targetTranslationMigrator.js` This module is already set up to migrate target translation that are being imported.

* [ ] update how translators are saved so we only store the name (Chris)
* [x] add migration step latest (and past) version(s) of manifest (Joel)
* [ ] link the migration module where appropriate in the dashboard `checklist` method removing duplicate code where necessary. (Chris)

**Comment by neutrinog** [comment]
@cdwhitfield73 are the target translations migrated on the fly when the app lists them? I was trying to find it unsuccessfully. Whenever we decide to work on this can you double check that and take a look at the module mentioned above? It will be better if we have a single migration point to maintain. The module above is designed to take in the path to the target translation  for processing and returns a promise so it should be easy to integrate.

**Comment by cdwhitfield73** [comment]
@neutrinog Joel, there is a function on the dashboard called "checklist" that goes through each project when the app loads and creates the project meta data in the format that the app requires based on the manifest file.  This function will always be necessary to some degree because there are some things not in the manifest file that the app needs and this function creates them (ie: fullname).  However, this function also currently serves as a migration tool as well to update old manifest versions to the current (ie: changing project_type to project.type, etc.)  For this portion, we could make a call to your migration module to make it cleaner, but currently that is not how it is set up.  Currently, the migration module is only being called when a project is imported/restored.  Also, besides adding this new change, the migration module is out of date already because we changed the manifest to a project object with name, id, type as properties from the old project_type method and the migrator was never updated to account for that.

**Comment by cdwhitfield73** [comment]
All of these issues can be resolved at one time as part of this issue, whenever it gets worked on.

**Comment by neutrinog** [comment]
sounds good. I added a checklist.
