### ISSUE TITLE
Create UI for Handling Merge Conflicts

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#379]
Restoring from a backup will merge changes between what you have in your project and the project file being imported. A UI change is needed to merge these changes together. (Issue already exists in Android 1290 https://github.com/unfoldingWord-dev/ts-android/issues/1290)

Blocked by #366 and #354

**Comment by neutrinog** [comment]
![merge](https://cloud.githubusercontent.com/assets/15789352/13091261/e74c1914-d4bf-11e5-989f-38eab6b1dac0.jpg)

**Comment by neutrinog** [comment]
this is also blocked until we can get the merging to work correctly so that the git merge code is injected into the text.

**Comment by cckozie** [comment]
Functionality works well, but suggest looking for a better icon. At first I though the one implemented was an alarm clock. Here are a few other possibilities:
![conflict1](https://cloud.githubusercontent.com/assets/8171759/17485846/86639488-5d54-11e6-8d03-1fdffef6e991.gif)
![conflict4](https://cloud.githubusercontent.com/assets/8171759/17485847/86686418-5d54-11e6-9786-47b228c42efe.jpg)
![conflict3](https://cloud.githubusercontent.com/assets/8171759/17485848/866a3c2a-5d54-11e6-9095-55e5c51aaab0.png)
![conflict2](https://cloud.githubusercontent.com/assets/8171759/17485849/866f24b0-5d54-11e6-8bdb-8a44148f3a56.png)

**Comment by cckozie** [comment]
Put on QA Hold until we discuss handling more than two text versions in a chunk.

**Comment by cdwhitfield73** [comment]
This has been reworked and can now handle as many merge conflicts combined together as you want!

**Comment by cckozie** [comment]
The message regarding chunks that have conflicts is misleading. It appears to refer to how many chunks were found to be in conflict between the existing project and the one that was just imported rather than the total number of chunks that have conflicts. I think we should modify the conflicts message to include one of these options: 1) The total number of chunks that have conflicts, 2) The number of NEW conflicts created by the import, or 3) Just report that there are conflicts but don't specify how many.

**Comment by klappy** [comment]
Option 2 sounds like the way to go.

**Comment by cckozie** [comment]
Option 2 was implemented. Marking as QA Passed.
