### ISSUE TITLE
Create UI for Active User login

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-desktop#450]
Jesse would like to see screens of this before pushing this out.

**Comment by neutrinog** [comment]
When a user starts the app we will collect their name or allow them to log into gogs. If they log into gogs and their account does not have a full name the app should collect that from them and update their account. If, rather than logging in, they provide their name and later log in their gogs full name will override what they provided earlier. Or again, if their gogs account does not have a full name we will use the given name to update their profile. We still need to design how to indicate who they are logged-in/translating as.

**Comment by neutrinog** [comment]
@cdwhitfield73 can we display the license agreement whenever a user is not currently logged in?

**Comment by neutrinog** [comment]
we now have a rough implementation of this.

**Comment by cckozie** [comment]
Tested on OSX

**Comment by cckozie** [comment]
If I log out at the last step of publishing in order to log in to my GOGS account, after logging in I'm sent back Home rather than being returned to the last publishing step.

**Comment by cckozie** [comment]
The verbiage on the "Cannot publish with a local login..." dialog should be changed to reference a git.door43.org account rather than just Door43.

**Comment by cckozie** [comment]
tA and any other related documentation and training materials need to be updated info for GOGS.
