### ISSUE TITLE
update gogs account creation to set the full_name when first creating the account

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#540]
The latest version of the gogs-client `0.1.0` library (and our api) now supports setting the full_name in `createUser`.

Also, we will begin using a "restricted" token in the app soon. This token will *only* be able to create users. Therefore we need to ensure the code is only using the admin token for account creation and nothing else.

**Comment by tjklemz** [comment]
@neutrinog Chris W. gave me the rundown on this. It will be a quick/easy update; just needs testing.

**Comment by cckozie** [comment]
What field(s) is it using to determine if the account already exists?

**Comment by neutrinog** [comment]
@cckozie it should fail on both the username and email address

**Comment by cdwhitfield73** [comment]
Not sure why this issue got QA Failed.  First of all, the issue was only for changing the way the full name field was set up.  Did this fail?  When I create a new account, the full name field is populated and returned correctly.  Second, it sounds like you were testing account already exists parameters.  When I try it, it stops me from creating a new account if either the username or the email have already been used, which is what we want.  Are you getting different results?

**Comment by tjklemz** [comment]
@cckozie ^^ bump.
