### ISSUE TITLE
project is not shown after im...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/ts-desktop#602]
Notes
======
project is not shown after import. It said the project was imported successuflly and there's a folder for it in the data dir but it is not shown in the app even after restarting.

Environment
======
Environment Key | Value
:--: | :--:
Version |8.0.0
Operating System | Linux
Platform | linux
Release | 4.5.0-2-amd64
Architecture | x64

Log History
======
```javascript
5/6/2016 2:23:54 PM E/ts-publish-publish.html:341:3: Error: 401 
5/17/2016 5:02:07 PM E/ts-publish-publish.html:304:3: Error: Cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.
5/25/2016 2:02:45 PM E/projects.js:78:26: TypeError: Cannot read property 'length' of undefined
5/25/2016 2:03:08 PM E/projects.js:78:26: TypeError: Cannot read property 'length' of undefined
5/25/2016 2:04:29 PM E/projects.js:78:26: TypeError: Cannot read property 'length' of undefined
5/25/2016 2:06:15 PM E/projects.js:78:26: TypeError: Cannot read property 'length' of undefined

```

**Comment by neutrinog** [comment]
Here's the archive. This is a backup from ts-android

[1464209778_en-x-demo1_phm_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/ts-desktop/files/282997/1464209778_en-x-demo1_phm_text_reg.tstudio.zip)

**Comment by neutrinog** [comment]
if you try to import it again then you get an error
```
Error: Failed to create temporary file '/pack_git2_rklnIt': Permission denied
```

**Comment by cdwhitfield73** [comment]
@neutrinog The problem with the first file is that there is no "finished_chunks" array in the manifest.  Why is that?  It says it is a package_version 6 manifest, it should have a blank array for that field, even if there are no finished chunks.  Is android not creating all the manifest fields up front unless there is data to go in them?  This will be a problem when trying to transfer them to desktop.

**Comment by cdwhitfield73** [comment]
@neutrinog Same problem with the second file

**Comment by cdwhitfield73** [comment]
Just to be clear, the import of these files (individually) was working.  The problem was occurring when trying to build the project meta data from the manifest.  It was failing because the finished chunks array was not present, therefore not showing the project in the project list.  I have added some error handling to account for the scenario of no finished chunks array so that the app will still be able to handle the project, although I still think android needs to make sure this array exists in all manifests, even if it is empty.  Both of these files now import and show up correctly in desktop.  There is another issue, however, when trying to merge these projects, which is creating the permissions error while trying to create a temporary file.  I still don't know why this is happening or how to fix it.

**Comment by cdwhitfield73** [comment]
The merging issue was resolved when we changed the git module to use native git rather than NodeGit.
