### ISSUE TITLE
Freezing on Duplication Project

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#618]
tS-D version 8.0.0
When I tried to create a new project - I got the message that it was a duplicate project. 
On the new project opening screen (where to choose the source translation) - it is all grayed out and there is no exit or way to click the menu.
There is Status: Idle in the bottom bar under the 3-dot menu icon.

![desktop error](https://cloud.githubusercontent.com/assets/9850185/15722485/fbcc6214-280b-11e6-838f-33f8589b8371.png)

I used Windows Task Manager to force the program to close.
After I restarted the program, the project was there with a source text. So, either I was trying to create a project that was already in existence OR I double clicked on the Bible book in error.

**Comment by cdwhitfield73** [comment]
Yes, this was caused by double clicking on the project, firing two instances of trying to create the project.  The second one gets the duplicate popup, but in the mean time, the first one is trying to load and causing problems.  I have added checking to not allow the second click to activate a new project.
