### ISSUE TITLE
App appears to have lost the source language selection when reopening a project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#661]
Created a new OBS project. Entered text in a few chunks and returned to the home screen. When I reopened the project I was presented with the source language selection screen. This seems to possibly only occur with some project. It happens with OBS, Genisis, and 3John, but doesn't happen with Titus.

**Comment by cckozie** [comment]
This appears to be somewhat intermittent on 9.0-11. It happened the first time I created a new Genesis project, but not the second or third time. It happened again the first time I created an Isaiah project, but not the second. It happened again the third time I created an Isaiah project, but then instead of choosing the source language again, I went back to the home screen. When I was prompted for the source language I noticed that the language I had previously selected was still selected, so it seems weird that it would prompt again when it already "knew" what I wanted.

**Comment by cdwhitfield73** [comment]
This one is a little puzzling because first of all, I can't duplicate it.  My theory right now is that this is related to the timing issues with the git commits slowing things down and the pauses in the busy signals.  The changes I made for issue #660 may clean this one up too.  Let's test this again which those changes and see if it still happens.
