### ISSUE TITLE
OSX v9.1 - Cannot send feedback

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#701]
After receiving an error when attempting to delete a project, I used the Feedback option to report the problem. When I came to Gitthub to add a comment to the feedback issue, I found that it didn't exisit here. The app indicated that the feedback had been successfully sent. I tried again later without having closed the app and it did work.
Not sure if this info is related or not:
![image](https://cloud.githubusercontent.com/assets/8171759/16494761/2a51fbe8-3eb0-11e6-95a2-3caad648519a.png)

**Comment by neutrinog** [comment]
@tjklemz did you have the private config file?

**Comment by tjklemz** [comment]
RE: the error. It looks like this is due to the "Developer Tools" button not being updated to use the new (internal) Electron API. It's a bug, but I don't think it's related, although it may have produced side-effects. IOW, it should be its own Github Issue.

@neutrinog yeah, I have the private config file which is up to date.

@cckozie I was able to submit several bug reports (all with the word Koz in them). The very first one I tried did not show up on Github. (It was titled "Koz finds all our problems".) I can't for the life of me find replicate the issue. I deleted the cache and everything.

What I can do is this: When the user submits feedback and it's successful, we get a URL to the Issue back. I can check to see if this exists; if not, I'll display the error.

**Comment by cckozie** [comment]
I had a second instance of the feedback not appearing on github. This one was also sent immediately after having received another error message in tS.

**Comment by cckozie** [comment]
9.1 build 23
I uploaded a project with no shared history to force an error message. I then tried to send feedback and got this message. At least now I am warned that it didn't work:)
![image](https://cloud.githubusercontent.com/assets/8171759/16669136/87866b2e-4459-11e6-8fda-3edb7207b8c9.png)

**Comment by cckozie** [comment]
It looks like I can make it fail consistently by attempting to delete a project from 9.1 build 22 that refuses to be deleted, and then try to send feedback. Here's what the console is showing:
![image](https://cloud.githubusercontent.com/assets/8171759/16669383/dc150d20-445a-11e6-8698-e249081859ab.png)

**Comment by cckozie** [comment]
I'm going to pass this and create a new issue that references it so we can possibly clean it up later.

**Comment by tjklemz** [comment]
If a project got locked in build 22, there's no way to unlock it, even from Finder. Build 23 should not lock a project, though. (We tested fairly thoroughly.)

Hope that makes sense.
