### ISSUE TITLE
When changing project type (or target language), a full merge is not performed as expected

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#744]
I restored a Bible project from door43.
I changed the text in chunk 1
I changed the project type from ULB to Reg (or changed target language)
I restored the same project again from door43
I changed the text in chunk 2
I changed the project type from ULB to Reg
tS warned me that it was going to merge the projects
What I see in the "merged" project is not what I expected. The chunk conflicts were not shown, but rather it looks like it just retains whatever text was the most recent entered for the respective chunks.

**Comment by cdwhitfield73** [comment]
This is because you are doing a merge of git histories...not a merge of text.  Both projects have the same git history from the point you brought them down from the server.  Then one project has new history that only affects chunk 1 and one project has new history that only affects chunk 2.  When you merge, both histories can merge together without issue, showing you the newest changes in history to both chunks.  This would be the expected results of a git merge.
