### ISSUE TITLE
Need to warn the user if the backup location is not accessible

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#746]
I changed the backup location to an external drive and then later removed the drive. The app continues to run and gives no warning to the user that the backup location is not accessible. Error messages do appear in the console log, but the user will not typically be aware of this.

**Comment by cdwhitfield73** [comment]
There are 2 times when it needs the backup location to be available to do an auto backup.  The first is on start up, when it backs up all projects.  The second is when a project is open, and it auto backs up that project every 10 minutes.  The first scenario (start up) was already checking the location and displaying a popup error message if not found.  The second scenario was the one that was happening behind the scenes and not warning the user.  There is now a popup dialog for this scenario as well.

**Comment by cckozie** [comment]
If I make a change to the text and then go to the home screen, the popup dialog comes up briefly but then goes away when the home screen is displayed. I think we should force the user to acknowledge the error by clicking the close button and not automatically dismissing the dialog when navigating to the home screen.

**Comment by cdwhitfield73** [comment]
Yes, I agree that would be ideal, but there are some technical road blocks to maintaining a popup dialog as you go from one mode to another.  And here are my thoughts on why it's not worth the effort to try and work around those roadblocks.  While the popup does just display briefly when you navigate from the project back to the home page, it will also pop up and stay up every time the app tries to auto backup the project, which is every 10 minutes starting 2 minutes after you open the project.  So as long as someone stays in a project for at least 2 minutes, which is the most likely scenario for a user (although not for a QA tester), they will see this popup and have to manually acknowledge it and close it at least once (and every 10 minutes until they fix the problem) before leaving the project.  So I felt that it was acceptable to have it just display briefly and then auto close at that point.  Also considering that this issue will only occur when someone is using an external drive for backups (which will be rare) AND that person has removed the external drive after opening the app (otherwise they get the message on startup as well) AND that they only open a project, make changes to it, and go back home in under two minutes AND that the worst thing that happens here is that the auto backup doesn't get saved (which aren't used for anything anyway), I consider this a very, very edge case.  @klappy If you want me to continue to work on this feature to fix this rare scenario, let me know.

**Comment by cckozie** [comment]
Is it really that hard to block the navigation to the home page until they have dismissed the dialog?

**Comment by klappy** [comment]
Let's circle back on this issue and address it in a future release.

**Comment by cckozie** [comment]
There is an OSX specific bug related to this that is now described in issue 802.
Marking as QA Passed and entering a new issue to deal with this original problem on navigating to the home page.
