### ISSUE TITLE
Notes, Words, and Questions tab are not shown for last chunk in Bible projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#751]
![image](https://cloud.githubusercontent.com/assets/8171759/16708988/4ad58040-45c9-11e6-92bc-f1190cf2345f.png)
And the UDB text is not displayed either.
OK in OBS projects

**Comment by cdwhitfield73** [comment]
There are two separate issues here.  The first is the lack of tabs for notes, words and questions.  While it seems like this would not be the case, the reason the tabs don't exist is because the data does not exist.  For every book that I have checked, there are no notes, words, or questions in the database for the last chunk.  The app is trying to find them correctly, but there aren't any.

The second issue is this:  When the only tab available for a chunk is the udb, it will appear blank until clicked on.  This is a timing issue with rendering the text in that tab and will be difficult to fix.  It is only a problem when the udb is the only tab, on other chunks, you have to click the tab before seeing it anyway, and then it renders.

**Comment by cdwhitfield73** [comment]
This issue has been resolved with the changes to the new database structure and the new resource containers.  The data for the last chunk is now available and showing up correctly.
