### ISSUE TITLE
Update to new Upload/Export Menu and Project Review mode

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#811]
Combine uploading, backing up, exporting to PDF and USFM into one menu.  Menu is accessible from Home Page on Info screen, from Translate mode in 3 dot menu, and from Project Review mode.  Change old Publish/Upload 4 step review process to a Project Review mode with two pages, project chunks and contributors.

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/18277222/4c2130de-7413-11e6-9707-821a7b3e9d87.png)
![image](https://cloud.githubusercontent.com/assets/8171759/18277243/615719d2-7413-11e6-93a4-c8cd3645d03e.png)
![image](https://cloud.githubusercontent.com/assets/8171759/18277617/b3890ce6-7414-11e6-8926-1eb9bbd17872.png)

Questions:
1. Do we want to have some descriptive text on the Upload/Export Options menu as per the whiteboard, or is that now contained in the smaller print under each menu option?
2. Should it be Export to Project File or Export Project file?
3. Is the descriptive text under Export to Project File what we want?
4. Do we want to retain the Print option on the 3-dot and Details menus?

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/18277740/227a880a-7415-11e6-943d-e681a0f484df.png)

**Comment by cckozie** [comment]
Did we decide that we did not want the option of clicking Next on the Project and Contributors pages when performing a Project Review?

**Comment by klappy** [comment]
Thanks for looking into this @cckozie. 

1. Let's ask @ChrisJarka to double check what she thinks about the current individual descriptions and see if they are enough.
2. "Export Project File" does sound better.
3. Same answer as 1, but wonder if we should communicate that is creates and saves a __ of your project.
4. I think we do want to retain the print option, I'm assuming you mean the print icon beside the delete button.

**Comment by cckozie** [comment]
Klappy - On #4 - It's both on the Details menu (as your referenced) and on the 3-dot Home page menu.

**Comment by cdwhitfield73** [comment]
My comments: Klappy and/or Christine were going to give me the exact text they wanted under each item.  I haven't gotten anything yet, so I just put something.  But it can be easily changed.  We did discuss that having a description under each item could replace the need for a paragraph at the top.  We also specifically discussed having the Print option in all locations as a separate item for the non-technical users that would not know to go look under "Export".  Also, except for maybe changing some text, I have already shown this to Christine and she has given her initial approval.

**Comment by ChrisJarka** [comment]
@cckozie in answer to your question: Did we decide that we did not want the option of clicking Next on the Project and Contributors pages when performing a Project Review?

There is no Next choice. Each option (in the past a step) can be either viewed and/or skipped.

**Comment by ChrisJarka** [comment]
_1. Do we want to have some descriptive text on the Upload/Export Options menu as per the whiteboard, or is that now contained in the smaller print under each menu option?_
We had discussed the information on the present last page before uploading as an option 
By uploading your project to your Door43 account, it can be:

- Downloaded by other translators
- Merged with other projects
- Used as an online backup

Is it possible to have a short space between the 'Upload' and 'Export' buttons to add in the above information? It does not need to be in bulleted format. Instead of above all of the buttons as shown on the whiteboard.
"By uploading the project to your Door43 account, the content is available to be downloaded by other translators, merged with other projects, or used as an online backup."
I think that there should be a reminder that the project is now going public. Of course - I don't know what the next screen looks like.

 _2. Should it be Export to Project File or Export Project file?_
My grammarian tells me that the 'to' is correct English.

 _3. Is the descriptive text under Export to Project File what we want?_
I don't think the end-user needs to know that it creates a .tstudio file. :) How about 'Creates a project file' ? 
 
 _4. Do we want to retain the Print option on the 3-dot and Details menus?_
As Chris W stated above - I vote very highly that we keep the extra option of printing on both of the 3-dot menus and in the project information window. I don't think the end user would look for an export process so they can print.

**Comment by cckozie** [comment]
Outcome of conversations with Christine:
1. This descriptive text for Upload to Door43 should be added starting on a new line under the current text: "By uploading the project to your Door43 account, the content is available to be downloaded by other translators, merged with other projects, or used as an online backup." If it isn't feasible to have this additional text on the "button", then it can be placed below the button but in that case must be visually separated from the other buttons by spacing or some other means.
2. Change the main text for Export to Project File to just "Export Project File"
3. Change its descriptive text to "Creates a copy of your project file"
4. Keep the printing option on both menus.
5. Add the Next button back on the Project and Contributor screens of Review project
6. Hide the menu options that are not relevant/supported for the project type. 
    -- Don't show print or export to pdf options for tA, Notes, Words, or Questions projects.
    -- Don't show export to USFM for tA, Notes, Words, Questions, or OBS projects.

**Comment by cdwhitfield73** [comment]
All the changes have been made per the last post above

**Comment by PhotoNomad0** [comment]
@neutrinog @ChrisJarka @klappy @cdwhitfield73 @cckozie - just some differences on ts-android:  - It looks like the current implementation of print actually does a send of the PDF, not a save.
- "Export to USFM" has option of saving to single .usfm file or split by chapters (then zipped together).

**Comment by cckozie** [comment]
Desktop text changes look good.
