### ISSUE TITLE
Modify workflow and messages for upload when there are pending changes on the server

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#813]
The workflow is described in ts-requirements issue 145. The actual user messages, and possible tweaks to the workflow, are TBD and will be supplied by Christine Jarka.

**Comment by cdwhitfield73** [comment]
The final workflow and messages were supplied in issue #840.  These changes have been made.

**Comment by cckozie** [comment]
If I have a project open and select to upload it to door43 where a project that doesn't share its history already exists, it does properly warn me and ask if I want to merge them. If I say YES, it does the merge and warns me about conflicts, but those conflicts do not show up in the project until I close it and then reopen it.

**Comment by cdwhitfield73** [comment]
Good point.  The only way for the changes to show up is to completely reload the project.  So I have added code so that when you say "Yes" to importing the changes, the app automatically navigates back to the home screen before importing.  Then after the import is complete, the user will have to re-open the project.
