### ISSUE TITLE
Add back tA support to the app

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/ts-desktop#824]
This is blocked by #823

**Comment by cckozie** [comment]
We either need to not show tA projects, or give an error message stating that we do not currently support Translation Academy projects. I'm checking with Christine to see what she prefers.
![image](https://cloud.githubusercontent.com/assets/8171759/19128329/86eb59cc-8b08-11e6-8172-025cc9895857.png)

**Comment by cdwhitfield73** [comment]
I have changed this so that the error message in the Project Load Failed box now reads..."We do not currently support this project type".  I decided to leave the project visible in the home list.  The project can still be uploaded to Door43, backed up, or deleted.  It just can't be viewed or edited in the app.

**Comment by cckozie** [comment]
Please change the message to:  At this time, translationAcademy translation projects are not supported.

**Comment by cdwhitfield73** [comment]
done
