### ISSUE TITLE
SPIKE: Research options for using custom fonts in printing

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#825]
Non roman characters are not working in our PDF's

**Comment by klappy** [comment]
Discussing this issue with BCS/OA while in India. It appears that the issue is likely more than just implementing custom fonts to be able to support Indic languages. Many of them even with the right fonts aren't able to render through many PDF generating tools/libraries even with supported fonts. 

There is one project that was created primarily out of this same need, not font support but supporting more languages, in particular Burmese. I'm told that if we can support Burmese, then we should be able to support any language. ElectronPDF is a command line tool built on node.js but is one of the few tools known to support this many languages. 

Read this article here on why they built it:
https://fraserxu.me/2015/08/20/pdf-generation-on-the-web/

**Comment by cdwhitfield73** [comment]
Thomas confirmed that there are not any other good pdf generating libraries that we could use to replace pdfkit.  One other possible solution is to generate the pdf's on the server through the api, but this would require users to upload their projects and have internet access in order to print, so this is not a good option.  Another solution is to generate an HTML rendered page of the entire project formatted properly and then use the native print dialog to allow users to either send the project to a printer or to a pdf generator.  This is the option we are going to pursue at this time.  The research portion is done, so this issue is closed.  The implementation will done with issue #842.
