### ISSUE TITLE
Projects not showing up in the repository when restoring from door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#869]
I had a repo that had no projects in it. I logged in as the user for that repo and uploaded two projects to it. I then selected Restore from Door43, and the project selection screen showed no available projects. I then selected Import from Doo43 and now see the two projects. When I return to Restore from Door43, I now can see the two projects.

**Comment by cdwhitfield73** [comment]
I'm hoping that whatever was causing this has gone away now that this option is no longer in the app.  The other possibility is that pre-filtering by the username was the cause and now it happens all the time when you Import from Door43, because we added that filter as a default.  Please test and let me know.

**Comment by cckozie** [comment]
Looks like there is still a problem here. Go through the steps to do an import from door43. On the Search for Projects dialog, enter qa5 as the user. Visually scan through the list of projects to find one based on Mark. None appear. Now enter mrk in the Project Name field and you will see that there is one.
If you look at the door43 repo you will see that there are 23 projects in the repo, but only 20 of them are listed on the import projects page in tS.

**Comment by cdwhitfield73** [comment]
@cckozie This is not a failure, but rather a limitation on our search.  I thought I had mentioned this before...but searching by user or by project does not return all results...it only returns 20 maximum (not sure how it decides which 20 either) and it starts with user.  So filtering by a user will show you up to 20 of their projects.  By then filtering by project, you will see up to 20 that match that filter, giving you better odds at finding what you want.  If you put in a partial user (like "q") you will only get 20 random results for users with a "q" in their name, but then it will show you up to 20 projects for each user, so you could have up to 400 results.  Slightly annoying, I guess, but that's all we can do.  The original problem for this issue was that it wasn't showing any results for a user with 2 or 3 projects.  If that continues, let me know.  But if you are seeing up to 20 projects per user, then the code is working correctly, even though it's not showing you the one you are looking for.

**Comment by cckozie** [comment]
I'm not sure what you mean by "our search". On Android it returns all of the projects.

**Comment by cckozie** [comment]
I received a note from Chuck Leisch asking for us to fix this. He is working with the MAST team in Puerto Rico and is searching on es-419 to merge their projects and is only seeing some of the projects available on door43.

**Comment by cdwhitfield73** [comment]
I did some further research on this.  The maximum number of results I can get at one time is 50, so I increased the limit variable from 20 to 50.  This means you will get up to 50 users that match your user criteria and then for each user, up to 50 of their repos that match your repo criteria. With most "reasonable" criteria, this should return most results.  If you leave user criteria blank and have a fairly generic repo criteria (like "en") you will NOT get anywhere close to all the results.  A note about Android from the comments above...they got 58 results for this particular search.  Desktop will now give you 50, not sure how Android got 58, but either way, if you go directly to the door43 website, you will see that there are hundreds of matches, so Android is not returning all results either.  In order to do this, we would have to initiate the "pagination" setup that appears on the website, where you return 50 at a time and have pages that you can go to NEXT.  This would require a significant amount of time and I do not believe it has a good return on investment, but that is your call @klappy .  We should discuss this some time in a meeting, so we can decide if this "failure" is acceptable or if we want to invest more time into this feature.

**Comment by cdwhitfield73** [comment]
maximum limit of 50 is set in build 73.  Removing Fail tag and adding Retest tag so you can confirm that.  If this is not an acceptable solution, then we should create a new issue to completely rebuild the "Search repos" element, using pagination.

**Comment by cckozie** [comment]
In build 74 I am now getting a maximum of 50 projects returned for the search. I'll mark this as Passed and create a new issue to implement pagination in a future release.
