### ISSUE TITLE
Problem loading source text on new projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#905]
I created a new project, selected the target language, selected the source language, and clicked Confirm. The "Loading Source, please wait... dialog appeared, but when it disappeared rather than showing the project, it showed the "Choose source translation(s) to begin reading and translating" screen. After selecting the source a second time it worked as expected. This happened on both Win32 and Win64, but not on OSX. I have not been able to duplicate it again on either platform. Could this be related to that problem?
![capture](https://cloud.githubusercontent.com/assets/8171759/20577356/83e2cb7a-b187-11e6-9d24-e298444fcbae.PNG)

**Comment by cckozie** [comment]
I may have found the issue on this one. Sometimes it takes a second or two for the selected source text to be moved to the Selected group. The CONFIRM link is enabled even if there are no sources selected, so I'm guessing that I may have clicked the CONFIRM link before the selected source had been moved to Selected. CONFIRM should only be enabled if one or more sources are selected.

**Comment by cdwhitfield73** [comment]
You are partly correct.  The issue here is that when you select a source for the first time, it has to activate (open) that resource container, which could take a few seconds.  During this time, clicking the confirm button would have created the problem.  I have added code to disable all buttons whenever you add (or remove) a source and then re-enable them once all the code has processed, just like it already does when you download a source.  This will prevent the issue you had from occurring.

However, we don't want to disable the confirm button just based on whether there are sources selected or not.  A user may wish to remove all selected sources and confirm that, which should work.
