### ISSUE TITLE
Git control codes show up in projects with conflicts when printing or exporting to USFM

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#920]
If I print or export to USFM a project that has conflicts, the git control codes show in the text of that output.

**Comment by cdwhitfield73** [comment]
Replacing the "git control codes" in the printouts with some user friendly text, like "***Conflict***" or something else should be fairly easy and would allow PDF's to be made with conflicts.  Exporting to USFM with conflicts is another story.  Since USFM is based on "markers", any chunk with conflicts will have duplicate verse markers, which would cause a total mess in the usfm file, as well as trying to re-import that file into the app.  I recommend we don't allow exporting to USFM when there are conflicts.

**Comment by klappy** [comment]
I would recommend that we ask users to address conflicts before exporting usfm for now. Or at least somehow give a warning if they are exporting with conflicts.

Let's go ahead and make the print text friendly, and create a new issue for USFM and address that one separately.

**Comment by cdwhitfield73** [comment]
Conflicts have been addressed in printing.

**Comment by cdwhitfield73** [comment]
Conflicts have been addressed in exporting usfm.  A dialog comes up telling the user to resolve conflicts before exporting is allowed.

**Comment by cckozie** [comment]
Works in build 85 in Windows.

**Comment by cckozie** [comment]
Works in build 83
