### ISSUE TITLE
Hard to read search parameter - V11#77

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-desktop#924]
In the Search for Project window (Import Options - Import from Door43) could 'Username' be changed to 'User Name'?

![username all one word](https://cloud.githubusercontent.com/assets/9850185/20847935/15ee058a-b89e-11e6-8fe0-651cead6b431.png)

**Comment by ChrisJarka** [comment]
Also - I found Project Name in the field to be not fully descriptive of what I could search for - since I could search by project name (any part of the project name) and by language code, too.
I see where project name is also visually the header for the list of project names so that is very helpful. (As with the User Name field that becomes the header for that list.)
There isn't much space in the field to add many more descriptors...

**Comment by cdwhitfield73** [comment]
@ChrisJarka You are right that "Project Name" sometimes implies just the book of the Bible part of the name.  Here it really means "Repo Name" as you can search for language, book, or even resource type, or a combination of any.  However, showing it as "Repo Name" might also be confusing.  What about "Translation Name" ?  Would that make sense to a user?  Other ideas?

**Comment by cdwhitfield73** [comment]
@ChrisJarka It also just dawned on me that the title of the entire box is called "Search for Projects", which then sort of makes sense to use the term "Project Name".  Since they have already chosen the option to "Import from Door43", maybe changing the title to "Search for Door43 Repositories" and then changing the text in the search box to "Repository Name" would work.  It would definitely be the most accurate definition of what you are doing, just don't know if it would be the most clear definition to some users.

**Comment by cckozie** [comment]
For more context, here is a screenshot from Android
![screenshot_2016-12-06-04-00-40](https://cloud.githubusercontent.com/assets/8171759/20900614/92036cc0-baf4-11e6-96c6-f50820d887f5.png)

**Comment by cckozie** [comment]
CJ says, change Project Name to Book or Language. Add User Name and Project Name as permanent headers above the listed projects.

**Comment by cckozie** [comment]
Looks good.
