### ISSUE TITLE
Running search feature is bogging down the system

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/ts-desktop#947]
The search feature was firing on every keystroke in edit mode, whether the search bar was open or not.  This was causing major delays in the displaying of characters while typing.  This became more and more of an issue the bigger the project was (more chunks to search through).  I have made changes to how and when the search is fired to eliminate these issues.

**Comment by cckozie** [comment]
The keyboard slowdown problem is vastly improved, but the fix is now causing issues with the search feature. I opened an OBS project and did some typing in one of the chunks. It worked fine. I then timed these activities.
1. Open the search bar, then click on the X to close the search bar. Took 9 seconds to close the search bar.
2. Open the search bar, then keu "the" into the search field. Took 9 seconds to display the matches.
Keystrokes and cursor clicks during the 9 seconds are all buffered until the 9 seconds has ended.
The delay seems to be related to the project size. It was less that 2 seconds in Philippians, but 55 seconds in Psalms.

**Comment by cdwhitfield73** [comment]
Yes, searching takes a while if the project is big.  I don't know if you ever tested it, but these times should not have changed from previous builds (they should have been slow too).  The only thing I changed now was reducing the frequency of when the search is fired, to eliminate some of the delays.  I will look into seeing if I can speed up the search.  The only other thing I could do is add a "spinner" to indicate when the search is working and maybe disable everything else until it is done.

**Comment by cckozie** [comment]
I hadn't done a lot of testing with large projects before, but I don't recall seeing the problem that once I open the search bar everything looks like it's locked for several seconds, even on my fastest machine. If I open the search bar and click the target or source radio button, it takes several seconds to switch, even if I never executed a search. Same with closing the search bar or pretty much anything else. Would all of these issues be solved if we made them click a "Search now" button after entering the criteria?

**Comment by cckozie** [comment]
I don't know if it is related, but I see another manifestation of slow response. I open a Psalms project (don't do anything with searching) and go into blind draft mode. I scroll to a untranslated chunk and copy the source text (highlight CTRL-C), click on the target card and paste in the copied text, then click on the source card again, it pauses 30 seconds before moving the source card to the foreground.

**Comment by cdwhitfield73** [comment]
Redesigned how the search function operates behind the scenes and the speed issues are gone.  All changes (opening and closing search bar, typing in search bar, switching between source and target, etc.) are now instantaneous on my machine, even in Psalms.
